oracle-livelabs/common

- related/related_sprints.json
QA test for new feature that will add related sprints based on tags (this is a final QA test)
> new feature: tagging for sprints (QA test)

- lintchecker/content/demo/adb-query/adb-query.md
- lintchecker/content/query-database/adb-query/adb-query.md
- lintchecker/content/sample-workshop/adb-query/adb-query.md
- lintchecker/vale/fixtures/checks/Repetition/test.md
- lintchecker/vale/fixtures/formats/subdir3/test.mdx
- lintchecker/vale/fixtures/formats/test.md
- lintchecker/vale/fixtures/formats/test.mdx
- lintchecker/vale/fixtures/formats/test.xyz
- lintchecker/vale/fixtures/plugins/test.md
- lintchecker/vale/fixtures/scopes/attr/test.md
- lintchecker/vale/fixtures/templates/test.md
LLAPEX-492 patching image and file paths
> LLAPEX-492 patching image and file paths

- .github/pull_request_template.md
> Testing PR templates

- .github/pull_request_template.md
1. Information in workshop is adequate and updated
4. Make sure the help email link in your manifest.json is set
Check here:
- Tenancy/Free Tier: https://oracle-livelabs.github.io/common/labs/cloud-login/cloud-login.md
- Sandbox/LiveLabs https://oracle-livelabs.github.io/common/labs/cloud-login/- cloud-login-livelabs2.md
- Desktop/noVNC: https://oracle-livelabs.github.io/common/labs/remote-desktop/using-novnc-remote-desktop.md
Check here:
- Tenancy/Free Tier: https://oracle-livelabs.github.io/common/labs/need-help/need-help-freetier.md
- Sandbox/LiveLabs: https://oracle-livelabs.github.io/common/labs/need-help/need-help-livelabs.md
- Desktop: https://oracle-livelabs.github.io/common/labs/need-help/need-help-livelabs.md
> Shortened checklist and updated requirements

- oracle-db-examples/README.md
Code examples for developer days
> New folder for developer tech days code examples

- sample-livelabs-templates/create-labs/labs/2-labs-github/2-labs-github.md
> remove invalid URL

- sample-livelabs-templates/create-labs/labs/4-labs-markdown-develop-content/4-labs-markdown-develop-content.md
> Update Oracle Video Hub URL

- sample-livelabs-templates/create-labs/labs/introduction/introduction.md
Updated Step by Step - Introduction - fixed typos and outdated details
> Updated Step by Step - Introduction - fixed typos and outdated details

- labs/database-setup/setup-sample-schema.md
- labs/setup-compute/setup-19c-freetier.md
- sample-livelabs-templates/create-labs/labs/4-labs-markdown-develop-content/4-labs-markdown-develop-content.md
- sample-livelabs-templates/create-labs/labs/6-labs-publish/6-labs-publish.md
- sample-livelabs-templates/create-labs/labs/introduction/introduction.md
- sample-livelabs-templates/create-labs/labs/livelabs-faq/livelabs-faq.md
- sample-livelabs-templates/create-labs/labs/need-help/need-help.md
- sample-livelabs-templates/sample-workshop-novnc/initialize-environment/initialize-environment.md
- sample-livelabs-templates/sample-workshop-novnc/tables/tables.md
- sample-livelabs-templates/sample-workshop/tables/tables.md
> Patch PAR URLs

- labs/need-help/need-help-freetier.md
- labs/need-help/need-help-livelabs.md
> Updated the need-help folder from common labs

- sample-livelabs-templates/create-labs/labs/4-labs-markdown-develop-content/4-labs-markdown-develop-content.md
> Changes of formatting for Step-by-Step Guide

- sample-livelabs-templates/create-labs/labs/2-labs-github/2-labs-github.md
- sample-livelabs-templates/create-labs/labs/3-labs-sync-github/3-labs-sync-github.md
> Changes of Step-by-Step Guide 

- sample-livelabs-templates/create-labs/labs/4-labs-markdown-develop-content/4-labs-markdown-develop-content.md
> Adding 3rd-party rule to step by step guide

- sample-livelabs-templates/create-labs/labs/introduction/github-introduction.md
Update link in step-by-step guide Introduction
> Update link in step-by-step guide

- building-blocks/blocks/oml/oml-conda/oml-conda.md
- building-blocks/scripts/generate-documentation.py
- building-blocks/tasks/adb/cleanup.md
Updates on generate documentations script
> Updates on generate documentation script

- labs/cloud-login/pt_BR-cloud-login.md
> Oci UI update 2025

- testing/introduction/introduction.md
Workflow changes + UI screenshots changes in the workshop.
> WMSID: Testing + OCI UI UPDATE 2025

- sample-livelabs-templates/create-labs/labs/12-labs-oci-ui-update/12-labs-oci-ui-update.md
WMS ID: Test + OCI UI UPDATE 2025
> WMS ID: Test + OCI UI UPDATE 2025

- sample-livelabs-templates/create-labs/labs/12-labs-oci-ui-update/12-labs-oci-ui-update.md
- testing/introduction/introduction.md
> Oci UI update 2025 - test

- labs/cloud-login/cloud-login-livelabs.md
- sample-livelabs-templates/create-labs/labs/7-labs-create-custom-image-for-marketplace/7-labs-create-custom-image-for-marketplace.md
> updating PARs - common lab
